# This is a basic workflow to help you get started with Actions

name: Build Artifact

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Caches local maven repository
      - name: Cache maven local repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Sets up java 8 with java FX
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8' # The JDK version to make available on the path.
          java-package: 'jdk+fx' # (jre, jdk, or jdk+fx) - defaults to jdk

      # Builds and installs the artifact
      - name: Build and Install
        run: mvn clean install

      # Uploads the Artifact to Github. You will be able to find it on your action workflow run
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: final-artifact
          path: target
